<?php
/**
 * PartnerCreditCheckRequestV2Model
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Capayable API V2
 *
 * API for Pay after delivery and Pay in 3 installments
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * PartnerCreditCheckRequestV2Model Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PartnerCreditCheckRequestV2Model implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PartnerCreditCheckRequestV2Model';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'credit_check_request' => '\Swagger\Client\Model\CreditCheckRequestV2Model',
        'shop_logo_url' => 'string',
        'shop_name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'credit_check_request' => null,
        'shop_logo_url' => null,
        'shop_name' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'credit_check_request' => 'CreditCheckRequest',
        'shop_logo_url' => 'ShopLogoUrl',
        'shop_name' => 'ShopName'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'credit_check_request' => 'setCreditCheckRequest',
        'shop_logo_url' => 'setShopLogoUrl',
        'shop_name' => 'setShopName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'credit_check_request' => 'getCreditCheckRequest',
        'shop_logo_url' => 'getShopLogoUrl',
        'shop_name' => 'getShopName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['credit_check_request'] = isset($data['credit_check_request']) ? $data['credit_check_request'] : null;
        $this->container['shop_logo_url'] = isset($data['shop_logo_url']) ? $data['shop_logo_url'] : null;
        $this->container['shop_name'] = isset($data['shop_name']) ? $data['shop_name'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['credit_check_request'] === null) {
            $invalidProperties[] = "'credit_check_request' can't be null";
        }
        if (!is_null($this->container['shop_logo_url']) && (mb_strlen($this->container['shop_logo_url']) > 1024)) {
            $invalidProperties[] = "invalid value for 'shop_logo_url', the character length must be smaller than or equal to 1024.";
        }

        if (!is_null($this->container['shop_logo_url']) && (mb_strlen($this->container['shop_logo_url']) < 0)) {
            $invalidProperties[] = "invalid value for 'shop_logo_url', the character length must be bigger than or equal to 0.";
        }

        if ($this->container['shop_name'] === null) {
            $invalidProperties[] = "'shop_name' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets credit_check_request
     *
     * @return \Swagger\Client\Model\CreditCheckRequestV2Model
     */
    public function getCreditCheckRequest()
    {
        return $this->container['credit_check_request'];
    }

    /**
     * Sets credit_check_request
     *
     * @param \Swagger\Client\Model\CreditCheckRequestV2Model $credit_check_request credit_check_request
     *
     * @return $this
     */
    public function setCreditCheckRequest($credit_check_request)
    {
        $this->container['credit_check_request'] = $credit_check_request;

        return $this;
    }

    /**
     * Gets shop_logo_url
     *
     * @return string
     */
    public function getShopLogoUrl()
    {
        return $this->container['shop_logo_url'];
    }

    /**
     * Sets shop_logo_url
     *
     * @param string $shop_logo_url shop_logo_url
     *
     * @return $this
     */
    public function setShopLogoUrl($shop_logo_url)
    {
        if (!is_null($shop_logo_url) && (mb_strlen($shop_logo_url) > 1024)) {
            throw new \InvalidArgumentException('invalid length for $shop_logo_url when calling PartnerCreditCheckRequestV2Model., must be smaller than or equal to 1024.');
        }
        if (!is_null($shop_logo_url) && (mb_strlen($shop_logo_url) < 0)) {
            throw new \InvalidArgumentException('invalid length for $shop_logo_url when calling PartnerCreditCheckRequestV2Model., must be bigger than or equal to 0.');
        }

        $this->container['shop_logo_url'] = $shop_logo_url;

        return $this;
    }

    /**
     * Gets shop_name
     *
     * @return string
     */
    public function getShopName()
    {
        return $this->container['shop_name'];
    }

    /**
     * Sets shop_name
     *
     * @param string $shop_name shop_name
     *
     * @return $this
     */
    public function setShopName($shop_name)
    {
        $this->container['shop_name'] = $shop_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


