<?php
/**
 * CreditCheckRequestV2ModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Capayable API V2
 *
 * API for Pay after delivery and Pay in 3 installments
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreditCheckRequestV2ModelTest Class Doc Comment
 *
 * @category    Class
 * @description CreditCheckRequestV2Model
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreditCheckRequestV2ModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreditCheckRequestV2Model"
     */
    public function testCreditCheckRequestV2Model()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "initials"
     */
    public function testPropertyInitials()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "birth_date"
     */
    public function testPropertyBirthDate()
    {
    }

    /**
     * Test attribute "street_name"
     */
    public function testPropertyStreetName()
    {
    }

    /**
     * Test attribute "house_number"
     */
    public function testPropertyHouseNumber()
    {
    }

    /**
     * Test attribute "house_number_suffix"
     */
    public function testPropertyHouseNumberSuffix()
    {
    }

    /**
     * Test attribute "zip_code"
     */
    public function testPropertyZipCode()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "country_code"
     */
    public function testPropertyCountryCode()
    {
    }

    /**
     * Test attribute "has_different_shipping_address"
     */
    public function testPropertyHasDifferentShippingAddress()
    {
    }

    /**
     * Test attribute "shipping_street_name"
     */
    public function testPropertyShippingStreetName()
    {
    }

    /**
     * Test attribute "shipping_house_number"
     */
    public function testPropertyShippingHouseNumber()
    {
    }

    /**
     * Test attribute "shipping_house_number_suffix"
     */
    public function testPropertyShippingHouseNumberSuffix()
    {
    }

    /**
     * Test attribute "shipping_zip_code"
     */
    public function testPropertyShippingZipCode()
    {
    }

    /**
     * Test attribute "shipping_city"
     */
    public function testPropertyShippingCity()
    {
    }

    /**
     * Test attribute "shipping_country_code"
     */
    public function testPropertyShippingCountryCode()
    {
    }

    /**
     * Test attribute "phone_number"
     */
    public function testPropertyPhoneNumber()
    {
    }

    /**
     * Test attribute "fax_number"
     */
    public function testPropertyFaxNumber()
    {
    }

    /**
     * Test attribute "email_address"
     */
    public function testPropertyEmailAddress()
    {
    }

    /**
     * Test attribute "ip_address"
     */
    public function testPropertyIpAddress()
    {
    }

    /**
     * Test attribute "is_corporation"
     */
    public function testPropertyIsCorporation()
    {
    }

    /**
     * Test attribute "is_sole_proprietor"
     */
    public function testPropertyIsSoleProprietor()
    {
    }

    /**
     * Test attribute "corporation_name"
     */
    public function testPropertyCorporationName()
    {
    }

    /**
     * Test attribute "co_c_number"
     */
    public function testPropertyCoCNumber()
    {
    }

    /**
     * Test attribute "is_final"
     */
    public function testPropertyIsFinal()
    {
    }

    /**
     * Test attribute "claim_amount"
     */
    public function testPropertyClaimAmount()
    {
    }

    /**
     * Test attribute "payment_method"
     */
    public function testPropertyPaymentMethod()
    {
    }
}
