<?php
/**
 * CreditCheckResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Capayable API V2
 *
 * API for Pay after delivery and Pay in 3 installments
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreditCheckResultTest Class Doc Comment
 *
 * @category    Class
 * @description CreditCheckResult
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreditCheckResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreditCheckResult"
     */
    public function testCreditCheckResult()
    {
    }

    /**
     * Test attribute "is_accepted"
     */
    public function testPropertyIsAccepted()
    {
    }

    /**
     * Test attribute "transaction_number"
     */
    public function testPropertyTransactionNumber()
    {
    }

    /**
     * Test attribute "refuse_reason"
     */
    public function testPropertyRefuseReason()
    {
    }

    /**
     * Test attribute "refuse_reason_translation"
     */
    public function testPropertyRefuseReasonTranslation()
    {
    }

    /**
     * Test attribute "refuse_contact_name"
     */
    public function testPropertyRefuseContactName()
    {
    }

    /**
     * Test attribute "refuse_contact_phone_number"
     */
    public function testPropertyRefuseContactPhoneNumber()
    {
    }

    /**
     * Test attribute "first_installment_amount"
     */
    public function testPropertyFirstInstallmentAmount()
    {
    }
}
