<?php
/**
 * InvoiceRequestV2ModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Capayable API V2
 *
 * API for Pay after delivery and Pay in 3 installments
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InvoiceRequestV2ModelTest Class Doc Comment
 *
 * @category    Class
 * @description InvoiceRequestV2Model
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvoiceRequestV2ModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InvoiceRequestV2Model"
     */
    public function testInvoiceRequestV2Model()
    {
    }

    /**
     * Test attribute "transaction_number"
     */
    public function testPropertyTransactionNumber()
    {
    }

    /**
     * Test attribute "invoice_number"
     */
    public function testPropertyInvoiceNumber()
    {
    }

    /**
     * Test attribute "invoice_date"
     */
    public function testPropertyInvoiceDate()
    {
    }

    /**
     * Test attribute "invoice_amount"
     */
    public function testPropertyInvoiceAmount()
    {
    }

    /**
     * Test attribute "invoice_description"
     */
    public function testPropertyInvoiceDescription()
    {
    }

    /**
     * Test attribute "invoice_pdf_submit_type"
     */
    public function testPropertyInvoicePdfSubmitType()
    {
    }

    /**
     * Test attribute "invoice_pdf_url"
     */
    public function testPropertyInvoicePdfUrl()
    {
    }

    /**
     * Test attribute "invoice_pdf_email_sent_date"
     */
    public function testPropertyInvoicePdfEmailSentDate()
    {
    }

    /**
     * Test attribute "invoice_pdf_from_email"
     */
    public function testPropertyInvoicePdfFromEmail()
    {
    }

    /**
     * Test attribute "invoice_pdf_email_subject"
     */
    public function testPropertyInvoicePdfEmailSubject()
    {
    }

    /**
     * Test attribute "extra_info"
     */
    public function testPropertyExtraInfo()
    {
    }

    /**
     * Test attribute "culture_code"
     */
    public function testPropertyCultureCode()
    {
    }

    /**
     * Test attribute "invoice_pdf_data"
     */
    public function testPropertyInvoicePdfData()
    {
    }
}
