<?php
/**
 * InvoiceCreditApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Capayable API V2
 *
 * API for Pay after delivery and Pay in 3 installments
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * InvoiceCreditApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InvoiceCreditApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for invoiceCreditV2Post
     *
     * # Register a return:  credit on invoice / refund  If a customer returns a product to the webshop, the shop can refund him.Therefore you can notify capayable of returns which result in a credit of the invoice.    If the invoice is ready (partially) paid, Capayable will do a regular (partial) refund. Otherwise the invoice is credited, so the customer has to pay less(or nothing). Either case is a concern for Capayable, not the shop.    You can do multiple invoice credit calls on a single invoice.The total amount can be somewhat larger than the original amount, so the shop can refund extra return shipping costs if desired.    Because Capayable starts reminding the customer after 2 weeks, returns after 14 days will NOT be accepted (Result = `EXCEEDS_PERIOD_LIMIT`). So, when using Capayable pay after delivery, customer has 14 days (counting from last delivery date, sent to Capayable as `InvoiceDate`) to return (part of) his order.    ### (Partially) undeliverable  If an order can only be partially sent, or not at all (because for instance the product is out of stock), then follow the same logic as with cancellations after invoice:   - Do an invoice call for the entire order  - Provide the actual invoice by url or BCC email  - Register an invoice credit for the amount of undeliverable products..
     *
     */
    public function testInvoiceCreditV2Post()
    {
    }
}
